### PR TITLE
remove timer as well, that's what is supposed to reset

### PR DESCRIPTION
**Pull request by liuxuan30**
I suppose calling reset should also remove the timer

### CODE REVIEW

**Comment by wongzigii** [comment]
:+1: Agree. Need some handy code to invalidate timer.

**Comment by mineschan** [comment]
You cannot do that cause when you're in process of counting, calling to reset will reset the time but the timer could still counting, like usual timer does ;)

**Comment by liuxuan30** [comment]
I don't know what you mean. BUT will you called it `reset` if not removing the timer? I fix this because a real world user case. I am not sure if you met different story on your side.

**Comment by mineschan** [comment]
Try to build the example, click start on example 4, and click reset while counting

**Comment by liuxuan30** [comment]
well.. then I mean I had my issue and fix. It's you call to decide.

**Comment by mineschan** [comment]
@liuxuan30 good to know

**Pull request closed without merging**
